#!/usr/bin/env python3
"""Plot compression loss landscapes and nominal parameter efficiency.

The input JSON is generated by ``scripts/compression_loss_landscape_probe.py``.
Both PDF (vector) and PNG outputs are written for each figure.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Iterable, Mapping, Sequence

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Rectangle


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "remote_logs" / "compression_loss_landscape_20260712.json"

PALETTE = {
    "blue": "#0072B2",
    "orange": "#E69F00",
    "green": "#009E73",
    "red": "#D55E00",
    "purple": "#CC79A7",
    "sky": "#56B4E9",
    "yellow": "#F0E442",
    "gray": "#777777",
    "black": "#222222",
}


def configure_style() -> None:
    mpl.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "font.size": 10.5,
            "axes.labelsize": 11,
            "xtick.labelsize": 9.5,
            "ytick.labelsize": 9.5,
            "legend.fontsize": 9,
            "axes.linewidth": 0.8,
            "lines.linewidth": 2.0,
            "lines.markersize": 5.5,
            "xtick.direction": "out",
            "ytick.direction": "out",
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "savefig.dpi": 300,
        }
    )


def panel_label(ax: plt.Axes, letter: str, text: str) -> None:
    ax.text(
        0.0,
        1.03,
        f"({letter}) {text}",
        transform=ax.transAxes,
        ha="left",
        va="bottom",
        fontsize=10.5,
        fontweight="bold",
    )


def save_pair(fig: plt.Figure, output_dir: Path, stem: str) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    for suffix in ("pdf", "png"):
        fig.savefig(output_dir / f"{stem}.{suffix}", bbox_inches="tight")


def mean(values: Iterable[float]) -> float:
    array = np.asarray(list(values), dtype=np.float64)
    return float(array.mean()) if array.size else float("nan")


def plot_loss_landscape(payload: Mapping[str, object], output_dir: Path) -> None:
    rows = payload["rows"]  # type: ignore[index]
    representative_keys = ("vit_ex0", "vit_ex1", "qwen_ex0", "qwen_ex1")
    labels = {
        str(example["key"]): str(example["label"])
        for example in payload["examples"]  # type: ignore[index]
    }
    gamma_values = sorted(
        {
            float(row["scale_gamma"])
            for row in rows  # type: ignore[assignment]
            if row["category"] == "scale_landscape"
        }
    )

    matrices: dict[str, tuple[list[int], np.ndarray]] = {}
    all_values: list[float] = []
    for key in representative_keys:
        selected = [
            row
            for row in rows  # type: ignore[assignment]
            if row["key"] == key
            and row["method"] == "block_scale_gamma_reoptimized"
        ]
        block_sizes = sorted({int(row["block_size"]) for row in selected})
        matrix = np.full((len(block_sizes), len(gamma_values)), np.nan, dtype=np.float64)
        for row in selected:
            y = block_sizes.index(int(row["block_size"]))
            x = gamma_values.index(float(row["scale_gamma"]))
            matrix[y, x] = float(row["normalized_mse"])
        matrices[key] = (block_sizes, matrix)
        all_values.extend(matrix[np.isfinite(matrix)].tolist())

    vmin = float(min(all_values))
    vmax = float(max(all_values))
    fig, axes = plt.subplots(2, 2, figsize=(12.6, 8.8), constrained_layout=True)
    image_handle = None
    for index, (ax, key) in enumerate(zip(axes.flat, representative_keys)):
        block_sizes, matrix = matrices[key]
        image_handle = ax.imshow(
            matrix,
            origin="lower",
            aspect="auto",
            interpolation="nearest",
            cmap="cividis_r",
            vmin=vmin,
            vmax=vmax,
        )
        ax.set_xticks(range(len(gamma_values)), [f"{value:g}" for value in gamma_values])
        ax.set_yticks(range(len(block_sizes)), [str(value) for value in block_sizes])
        ax.set_xlabel(r"Block-scale heterogeneity gain $\gamma$")
        ax.set_ylabel("Block size $b$")
        panel_label(ax, chr(ord("a") + index), labels[key])

        threshold = 0.5 * (vmin + vmax)
        for y in range(matrix.shape[0]):
            for x in range(matrix.shape[1]):
                value = matrix[y, x]
                ax.text(
                    x,
                    y,
                    f"{value:.2f}",
                    ha="center",
                    va="center",
                    fontsize=7.4,
                    color="white" if value > threshold else "black",
                )
        if 4 in block_sizes and 1.0 in gamma_values:
            ax.add_patch(
                Rectangle(
                    (gamma_values.index(1.0) - 0.48, block_sizes.index(4) - 0.48),
                    0.96,
                    0.96,
                    fill=False,
                    edgecolor=PALETTE["red"],
                    linewidth=2.1,
                )
            )
        ax.grid(False)

    assert image_handle is not None
    colorbar = fig.colorbar(image_handle, ax=axes, shrink=0.88, pad=0.025)
    colorbar.set_label("Attention NRMSE after clip + row normalization")
    fig.text(
        0.5,
        -0.015,
        "Each cell re-fits the shared kernel to the target map; red outline marks the common b=4, γ=1 diagnostic.",
        ha="center",
        va="top",
        fontsize=9.2,
    )
    save_pair(fig, output_dir, "fig22_block_scale_loss_landscape")
    plt.close(fig)


def aggregate_by(
    rows: Sequence[Mapping[str, object]],
    method: str,
    block_size: int = 4,
) -> tuple[float, float]:
    selected = [
        row
        for row in rows
        if row["method"] == method and row.get("block_size") == block_size
    ]
    return (
        mean(float(row["parameter_fraction_of_dense_fp16"]) for row in selected),
        mean(float(row["normalized_mse"]) for row in selected),
    )


def plot_parameter_efficiency(payload: Mapping[str, object], output_dir: Path) -> None:
    rows: list[dict] = payload["rows"]  # type: ignore[assignment]
    summary: Mapping[str, object] = payload["summary"]  # type: ignore[assignment]
    fig, axes = plt.subplots(3, 2, figsize=(13.0, 13.9), constrained_layout=True)

    # (a) One-dimensional scale landscape at the common block size.
    ax = axes[0, 0]
    curve_specs = (
        ("block_scale_gamma_fixed_kernel", "Frozen shared shape", PALETTE["blue"], "o"),
        ("block_scale_gamma_reoptimized", "Kernel re-fit at each γ", PALETTE["orange"], "s"),
    )
    for method, label, color, marker in curve_specs:
        selected = [
            row
            for row in rows
            if row["method"] == method and row.get("block_size") == 4
        ]
        gammas = sorted({float(row["scale_gamma"]) for row in selected})
        grouped = {
            gamma: [
                float(row["normalized_mse"])
                for row in selected
                if float(row["scale_gamma"]) == gamma
            ]
            for gamma in gammas
        }
        means = np.asarray([mean(grouped[gamma]) for gamma in gammas])
        lows = np.asarray([min(grouped[gamma]) for gamma in gammas])
        highs = np.asarray([max(grouped[gamma]) for gamma in gammas])
        ax.fill_between(gammas, lows, highs, color=color, alpha=0.12, linewidth=0)
        ax.plot(gammas, means, color=color, marker=marker, label=label)
    ax.axvline(1.0, color=PALETTE["gray"], linestyle="--", linewidth=1.2)
    ax.set_xlabel(r"Block-scale heterogeneity gain $\gamma$ (b=4)")
    ax.set_ylabel("Mean attention NRMSE")
    ax.set_xlim(min(gammas), max(gammas))
    ax.legend(frameon=False, loc="upper right")
    ax.grid(True, alpha=0.23)
    panel_label(ax, "a", "Scale-strength profile (band = map range)")

    # (b) Quantization scale granularity.
    ax = axes[0, 1]
    scheme_specs = (
        ("global", "Global scale", PALETTE["red"], "o"),
        ("block_row", "Query-block-row scale", PALETTE["blue"], "s"),
        ("per_block", "Per-block scale", PALETTE["green"], "^"),
    )
    quant_summary = summary["quantization_b4"]  # type: ignore[index]
    for scheme, label, color, marker in scheme_specs:
        selected = [row for row in quant_summary if row["scale_scheme"] == scheme]
        selected.sort(key=lambda row: int(row["bits"]))
        ax.plot(
            [int(row["bits"]) for row in selected],
            [float(row["mean_normalized_mse"]) for row in selected],
            color=color,
            marker=marker,
            label=label,
        )
    independent_loss = aggregate_by(rows, "independent_block_circulant")[1]
    ax.axhline(
        independent_loss,
        color=PALETTE["black"],
        linestyle=":",
        linewidth=1.5,
        label="FP16-equivalent independent",
    )
    ax.set_yscale("log")
    ax.set_xlabel("Kernel code bits (FP16 scales included)")
    ax.set_ylabel("Mean attention NRMSE (log scale)")
    ax.set_xticks([2, 3, 4, 6, 8])
    ax.grid(True, which="both", alpha=0.23)
    ax.legend(frameon=False, loc="upper right")
    panel_label(ax, "b", "Scale granularity dominates low-bit accuracy")

    # (c) Empirical per-target Pareto points under nominal ideal packing.
    ax = axes[1, 0]
    category_specs = {
        "backbone": ("Backbone", PALETTE["blue"], "o"),
        "quantization": ("Quantized", PALETTE["green"], "s"),
        "sequential_compensation_factorial": ("Sequential compensation", PALETTE["orange"], "^"),
        "budget_capped_compensation": ("Budget-capped/order control", PALETTE["purple"], "D"),
    }
    for category, (label, color, marker) in category_specs.items():
        selected = [
            row
            for row in rows
            if row["category"] == category
            and float(row["parameter_fraction_of_dense_fp16"]) > 0
            and float(row["normalized_mse"]) > 0
        ]
        ax.scatter(
            [float(row["parameter_fraction_of_dense_fp16"]) for row in selected],
            [float(row["normalized_mse"]) for row in selected],
            s=11,
            color=color,
            marker=marker,
            alpha=0.10,
            linewidths=0,
        )
        frontier = [row for row in selected if bool(row.get("pareto_nrmse"))]
        ax.scatter(
            [float(row["parameter_fraction_of_dense_fp16"]) for row in frontier],
            [float(row["normalized_mse"]) for row in frontier],
            s=24,
            facecolors=color,
            edgecolors="white",
            linewidths=0.35,
            marker=marker,
            alpha=0.7,
            label=label,
        )
    for method, short, offset in (
        ("column_block_scale", "column scale", (4, -14)),
        ("block_scale_rank1", "full block scale", (4, 4)),
        ("independent_block_circulant", "independent", (4, 4)),
        ("budget_capped_sparse_component_first", "sparse first*", (4, -12)),
    ):
        x, y = aggregate_by(rows, method)
        ax.annotate(short, (x, y), xytext=offset, textcoords="offset points", fontsize=8)
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlim(3e-4, 1.15)
    ax.set_ylim(8e-3, 5.0)
    ax.set_xlabel("Nominal payload bits / dense FP16 bits")
    ax.set_ylabel("Attention NRMSE")
    ax.grid(True, which="both", alpha=0.20)
    ax.legend(frameon=False, loc="lower left", ncol=1)
    ax.text(
        0.98,
        0.98,
        "* target top-k; all colored frontier points\nare per-target empirical diagnostics\n0-bit uniform endpoint omitted on log-x",
        transform=ax.transAxes,
        ha="right",
        va="top",
        fontsize=8.4,
    )
    panel_label(ax, "c", "Enumerated target-fit Pareto (not deployment cost)")

    # (d) Same bit cap, explicit fit-order control.
    ax = axes[1, 1]
    capped = {
        str(row["method"]): row
        for row in summary["budget_capped_b4"]  # type: ignore[index]
    }
    methods = ("sink", "lowrank", "sparse")
    x = np.arange(len(methods), dtype=np.float64)
    width = 0.31
    backbone_first = [
        float(capped[f"budget_capped_{method}_backbone_first"]["mean_normalized_mse"])
        for method in methods
    ]
    component_first = [
        float(capped[f"budget_capped_{method}_component_first"]["mean_normalized_mse"])
        for method in methods
    ]
    ax.bar(
        x - width / 2,
        backbone_first,
        width,
        color=PALETTE["sky"],
        label="Backbone → component",
    )
    ax.bar(
        x + width / 2,
        component_first,
        width,
        color=PALETTE["orange"],
        label="Component → backbone",
    )
    base_loss = float(capped["block_scale_rank1"]["mean_normalized_mse"])
    independent_loss = float(capped["independent_block_circulant"]["mean_normalized_mse"])
    ax.axhline(base_loss, color=PALETTE["gray"], linestyle="--", linewidth=1.2, label="Block scale (6.3%)")
    ax.axhline(independent_loss, color=PALETTE["black"], linestyle=":", linewidth=1.4, label="Independent (25%)")
    ax.set_xticks(x, ["Sink", "Low-rank", "Sparse"])
    ax.set_ylabel("Mean attention NRMSE")
    ax.set_ylim(0.0, 0.66)
    ax.grid(True, axis="y", alpha=0.23)
    ax.legend(frameon=False, loc="upper right")
    for xpos, left, right in zip(x, backbone_first, component_first):
        ax.text(xpos - width / 2, left + 0.012, f"{left:.3f}", ha="center", va="bottom", fontsize=8)
        ax.text(xpos + width / 2, right + 0.012, f"{right:.3f}", ha="center", va="bottom", fontsize=8)
    panel_label(ax, "d", "Same ~25% cap, large greedy fit-order effect")

    # (e) Fixed-dose sequential factorial efficiency and local-component pairs.
    ax = axes[2, 0]
    factorial = summary["sequential_compensation_factorial_b4"]  # type: ignore[index]
    by_mask = {int(row["mask"]): row for row in factorial}
    for mask in range(8):
        left = by_mask[mask]
        right = by_mask[mask | 4]
        ax.plot(
            [float(left["mean_parameter_fraction"]), float(right["mean_parameter_fraction"])],
            [float(left["mean_normalized_mse"]), float(right["mean_normalized_mse"])],
            color=PALETTE["gray"],
            linewidth=0.9,
            alpha=0.65,
        )
    without_local = [row for row in factorial if not (int(row["mask"]) & 4)]
    with_local = [row for row in factorial if int(row["mask"]) & 4]
    ax.scatter(
        [float(row["mean_parameter_fraction"]) for row in without_local],
        [float(row["mean_normalized_mse"]) for row in without_local],
        color=PALETTE["blue"],
        marker="o",
        s=42,
        label="Without extra local",
    )
    ax.scatter(
        [float(row["mean_parameter_fraction"]) for row in with_local],
        [float(row["mean_normalized_mse"]) for row in with_local],
        color=PALETTE["red"],
        marker="x",
        s=48,
        linewidths=1.5,
        label="With extra local",
    )
    abbreviations = {
        0: "base",
        1: "S",
        2: "LR",
        8: "SP",
        9: "S+SP",
        11: "S+LR+SP",
        15: "all",
    }
    for mask, label in abbreviations.items():
        row = by_mask[mask]
        ax.annotate(
            label,
            (float(row["mean_parameter_fraction"]), float(row["mean_normalized_mse"])),
            xytext=(4, 4),
            textcoords="offset points",
            fontsize=8.2,
        )
    ax.set_xlabel("Nominal payload bits / dense FP16 bits")
    ax.set_ylabel("Mean attention NRMSE")
    ax.grid(True, alpha=0.23)
    ax.legend(frameon=False, loc="upper right")
    panel_label(ax, "e", "Fixed-dose sequential compensation")

    # (f) Saved true-V anchors: matrix loss is useful but not identical.
    ax = axes[2, 1]
    anchors = [
        row
        for row in payload["true_v_anchors"]  # type: ignore[index]
        if row["method"] in {
            "grid_cyclic_bccb",
            "flat_block_circulant",
            "permuted_flat_block_circulant",
            "monarch_like_mask_proxy",
            "hybrid_balanced",
        }
    ]
    groups = (
        (
            "Saved exact/slice outputs",
            [
                row
                for row in anchors
                if not str(row["method"]).startswith("hybrid")
                and not bool(row.get("is_attention_only_rollout"))
            ],
            PALETTE["blue"],
            "o",
        ),
        (
            "Saved attention-only rollout",
            [
                row
                for row in anchors
                if not str(row["method"]).startswith("hybrid")
                and bool(row.get("is_attention_only_rollout"))
            ],
            PALETTE["purple"],
            "^",
        ),
        (
            "Earlier oracle hybrid-balanced",
            [row for row in anchors if row["method"] == "hybrid_balanced"],
            PALETTE["orange"],
            "D",
        ),
    )
    for label, selected, color, marker in groups:
        ax.scatter(
            [float(row["relative_fro_error"]) for row in selected],
            [float(row["true_v_output_relative_error"]) for row in selected],
            s=38,
            color=color,
            marker=marker,
            alpha=0.78,
            edgecolors="white",
            linewidths=0.4,
            label=label,
        )
    x_values = np.asarray([float(row["relative_fro_error"]) for row in anchors])
    y_values = np.asarray([float(row["true_v_output_relative_error"]) for row in anchors])
    correlation = float(np.corrcoef(x_values, y_values)[0, 1])
    diagonal = np.geomspace(0.02, 1.3, 100)
    ax.plot(diagonal, diagonal, color=PALETTE["gray"], linestyle="--", linewidth=1.1)
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlim(0.02, 1.3)
    ax.set_ylim(0.02, 1.3)
    ax.set_xlabel(r"Saved attention relative Frobenius error")
    ax.set_ylabel(r"Saved true-$V$ output relative error")
    ax.grid(True, which="both", alpha=0.20)
    ax.legend(frameon=False, loc="upper left")
    ax.text(
        0.98,
        0.05,
        f"Pearson r = {correlation:.2f}\n(mixed saved scopes; new variants lack V)",
        transform=ax.transAxes,
        ha="right",
        va="bottom",
        fontsize=9,
    )
    panel_label(ax, "f", "True-V anchors are a separate validation layer")

    save_pair(fig, output_dir, "fig23_compression_parameter_efficiency")
    plt.close(fig)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-json", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output-dir", type=Path, default=ROOT / "figures")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    configure_style()
    payload = json.loads(args.input_json.read_text(encoding="utf-8"))
    plot_loss_landscape(payload, args.output_dir)
    plot_parameter_efficiency(payload, args.output_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
